version: "3.8"
services:
  orchestrator:
    build:
      dockerfile: orchestrator.Dockerfile
    environment:
      TZ: Europe/Kiev
    env_file: .env
    depends_on:
      - db
      - mongodb
  
  worker:
    build:
      dockerfile: worker.Dockerfile
    environment:
      TZ: Europe/Kiev
    env_file: .env
    depends_on:
      - db
      - mongodb
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5435:5432
    restart: always
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      -  ./data:/data/db

